[package]
name = "fishstick-stm32f103"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fishstick = { path = "../fishstick" }

[[bin]]
name = "fishstick-stm32f103"
path = "src/main.rs"
